version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: "redis-db"
    ports:
      - "6379:6379"

  app:
    build: ./server
    container_name: "node-app"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis