version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: "redis-db"
    ports:
      - "6379:6379"

  app:
    build: ./server
    container_name: "node-app"
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  team1:
    build: ./telemetry-generator
    container_name: "telemetry-generator-1"
    depends_on:
      - app
    environment:
      API_URL: http://node-app:3000/api/send_telemetry_data
      TEAM_NUMBER: 1


  team2:
    build: ./telemetry-generator
    container_name: "telemetry-generator-2"
    depends_on:
      - app
    environment:
      API_URL: http://node-app:3000/api/send_telemetry_data
      TEAM_NUMBER: 2

  team3:
    build: ./telemetry-generator
    container_name: "telemetry-generator-3"
    depends_on:
      - app
    environment:
      API_URL: http://node-app:3000/api/send_telemetry_data
      TEAM_NUMBER: 3

  team4:
    build: ./telemetry-generator
    container_name: "telemetry-generator-4"
    depends_on:
      - app
    environment:
      API_URL: http://node-app:3000/api/send_telemetry_data
      TEAM_NUMBER: 4
